--操作日志
CREATE TABLE OPERATION_LOG (
    ID INT NOT NULL AUTO_INCREMENT,
    MODULE VARCHAR(30),
    IDENTIFIER VARCHAR(30),
    USERNAME VARCHAR(30),
    OPERATE_TIME TIMESTAMP NOT NULL,
    OPERATION VARCHAR(30),
    COLUMNS TEXT,
    PRIMARY KEY (ID)
);